name: Build & Push Web to GHCR
on:
  push:
    branches: [master]
    #paths:
      #- 'fd.attendai.web/**'
    workflow_dispatch: {}            # 手动运行按钮
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fd.attendai.web
    permissions:
      contents: read
      packages: write # 允许推送到 GHCR（使用内置 GITHUB_TOKEN）
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64 # 如果需要 arm64 一起发：linux/amd64,linux/arm64
          tags: |
            ghcr.io/findingdata/fd.attendai.web:latest
            ghcr.io/findingdata/fd.attendai.web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
